version: "3"

services:
  client: 
    build: ./client
    ports:
      -"3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend: 
    build: ./backend
    ports:
      -"5000:5000"
    depends_on:
      - database

  database:
    image: mongo
    ports:
      -"27017:27017"
    volumes:
      - data:/data/db